name: hello-world
on: workflow_dispatch
jobs:
  my-job:
    runs-on: macos-latest
    steps:
      - name: my-step
        run: |
         sw_vers
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest  
      - name: my-step2
        run: |
         sw_vers
